create database edtech_project;
use edtech_project;
-- 1. Find total revenue generated by each course category. Sort highest to lowest.
select c.category ,sum(amount_paid) as revenue from payments p 
inner join courses c
on p.course_id = c.course_id
group by c.category
order by revenue desc;

-- 2. Find countries where total revenue exceeds 5,000,000.
select s.country ,sum(amount_paid) as revenue from payments p
inner join students s 
on p.student_id = s.student_id
group by country having revenue > 5000000
order by revenue desc;

-- 3. Find courses whose completion rate is greater than overall completion rate.
select c.course_name , avg(case when e.completion_status = 'Completed' then 1 else 0 end) 
as avg_completion_rate from enrollments e
inner join courses c 
on e.course_id = c.course_id
group by course_name
having avg(case when e.completion_status = 'Completed' then 1 else 0 end)  >
(select  avg(case when e.completion_status = 'Completed' then 1 else 0 end) 
from enrollments e);

-- 4.Rank courses based on total revenue and return top 5.
with revenue_by_courses as(
select c.course_name ,sum(amount_paid) as revenue from payments p 
inner join courses c
on p.course_id = c.course_id
group by c.course_name
) 
select *, 
dense_rank() over(order by revenue desc) as rnk
from revenue_by_courses
limit 5;


-- 5. Find top 3 revenue-generating courses within each category.
with revenue_by_courses as(
select  c.category, c.course_name ,sum(amount_paid) as revenue from payments p 
inner join courses c
on p.course_id = c.course_id
group by c.course_name,c.category
) 
select *from( 
select *,
dense_rank() over(partition by category order by revenue desc ) as rnk
from revenue_by_courses) t
where rnk <=3;

-- 6.Show total revenue generated per month.
select date_format(e.enrollment_date,'%Y-%m') as month,sum(p.amount_paid) as revenue from payments p
join enrollments e on e.student_id = p.student_id
group by date_format(e.enrollment_date,'%Y-%m')
order by month;

-- 7. Show each category’s revenue and compare it with overall average revenue.
with category_revenue as(
select c.category, sum(p.amount_paid)as revenue from payments p 
inner join courses c
on c.course_id =p.course_id
group by c.category
)
select category, revenue, (select avg(revenue) from category_revenue) as overall_revenue, 
case when revenue > (select avg(revenue) from category_revenue) 
then 'Above average'
else 'Below average'
end as comparison
from category_revenue;

-- 8.Calculate running total of revenue ordered by enrollment_date.
with daily_revenue as (
select e.enrollment_date,sum(p.amount_paid) as revenue from payments p
join enrollments e
on p.student_id = e.student_id
group by e.enrollment_date
)
select *,sum(revenue) over (order by enrollment_date) as running_total
from daily_revenue;

-- 9.Show each month’s revenue and difference from previous month.
with monthly_revenue as (
select date_format(e.enrollment_date,'%Y-%m') as month,sum(p.amount_paid) as revenue from payments p
join enrollments e on e.student_id = p.student_id
group by date_format(e.enrollment_date,'%Y-%m')
)
select month, revenue, 
lag(revenue) over (order by month) as previous_month_revenue,
revenue - lag(revenue) over (order by month) as revenue_differnce 
from monthly_revenue; 

-- Classify students:
-- High spender (> 2000)
-- Medium spender (1000–2000)
-- Low spender (< 1000)

with student_spending as(
select s.student_id, s.student_name,sum(p.amount_paid) as total_spent from payments p 
inner join students s
on s.student_id = p.student_id
group by student_id, student_name)

select student_name, total_spent, 
case when total_spent > 20000 then 'High spender' 
when total_spent between 1000 and 2000 then 'Medium spender'
else 'Low spender'
end as soending_category
from student_spending;





